version: "3.8"
services:
  rvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rvc
    volumes:
      - ./weights:/app/assets/weights
      - ./opt:/app/opt
      - C:\Users\tengr\Desktop\rvcwebui\train:/app/train # Training dataset
      - C:\Users\tengr\Desktop\rvcwebui\audio:/app/audio # Audio for voice conversion
    ports:
      - 7865:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
